export const GET_CATAGORIES_PENDING = "GET_CATEGORIES_PENDING";
export const GET_CATAGORIES_FAILED = "GET_CATEGORIES_FAILED";
export const GET_CATAGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_SLIDER_PENDING = "GET_SLIDER_PENDING";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_FAILED = "GET_SLIDER_FAILED";
